-- MySQL Script generated by MySQL Workbench
-- Sat May  9 09:27:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema point_of_sale
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `point_of_sale` ;

-- -----------------------------------------------------
-- Schema point_of_sale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `point_of_sale` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `point_of_sale` ;

-- -----------------------------------------------------
-- Table `point_of_sale`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `point_of_sale`.`Employee` ;

CREATE TABLE IF NOT EXISTS `point_of_sale`.`Employee` (
  `Employee_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Date_of_Birth` DATETIME NULL,
  `Gender` ENUM('M', 'F') NULL,
  `Street Address` VARCHAR(120) NULL,
  `City` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `point_of_sale`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `point_of_sale`.`Transaction` (
  `Transaction_ID` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`Transaction_ID`, `Employee_ID`),
  UNIQUE INDEX `Transaction_ID_UNIQUE` (`Transaction_ID` ASC),
  INDEX `Employee_ID_idx` (`Employee_ID` ASC),
  CONSTRAINT `Employee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `point_of_sale`.`Employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `point_of_sale`.`Product` ;

CREATE TABLE IF NOT EXISTS `point_of_sale`.`Product` (
  `Product_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Category` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  PRIMARY KEY (`Product_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`ItemSold`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `point_of_sale`.`ItemSold` ;

CREATE TABLE IF NOT EXISTS `point_of_sale`.`ItemSold` (
  `ItemSold_ID` INT NOT NULL,
  `Transaction_ID` INT NULL,
  `Product_ID` INT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`ItemSold_ID`),
  INDEX `Transaction_ID_idx` (`Transaction_ID` ASC),
  INDEX `Product_ID_idx` (`Product_ID` ASC),
  CONSTRAINT `Transaction_ID`
    FOREIGN KEY (`Transaction_ID`)
    REFERENCES `point_of_sale`.`Transaction` (`Transaction_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_ID`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `point_of_sale`.`Product` (`Product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
