-- MySQL Script generated by MySQL Workbench
-- Fri May  8 16:00:28 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Employee_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(120) NULL,
  `DOB` DATETIME NULL,
  `Picture` BLOB NULL,
  `Gender` ENUM('M', 'F') NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `Transaction_ID` INT NOT NULL,
  `Employee_ID` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  PRIMARY KEY (`Transaction_ID`, `Employee_ID`),
  UNIQUE INDEX `Transaction_ID_UNIQUE` (`Transaction_ID` ASC),
  INDEX `Employee_ID_idx` (`Employee_ID` ASC),
  CONSTRAINT `Employee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Descripiton` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `Picture` BLOB NULL,
  PRIMARY KEY (`Product_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemSold`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemSold` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemSold` (
  `ItemSold_ID` INT NOT NULL,
  `Transaction_ID` INT NULL,
  `Product_ID` INT NULL,
  PRIMARY KEY (`ItemSold_ID`),
  INDEX `Transaction_ID_idx` (`Transaction_ID` ASC),
  INDEX `Product_ID_idx` (`Product_ID` ASC),
  CONSTRAINT `Transaction_ID`
    FOREIGN KEY (`Transaction_ID`)
    REFERENCES `mydb`.`Transaction` (`Transaction_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_ID`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `mydb`.`Product` (`Product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
